name: C++ Build
permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu]
        arch: [x86_64, x86, arm64]
        compiler: [g++-15, clang++-21]
        optimize: [0, 1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcriterion-dev

      - name: Install toolchain
        if: matrix.os == 'ubuntu'
        run: |
          ./ci/setupToolchain.sh ${{ matrix.compiler }}

      - name: Build and run tests
        run: |
          make check CXX=${{ matrix.compiler }} OPTIMIZE=${{ matrix.optimize }}
